/* 
Josue Amaya 0901-19-12421
Asignacion de cursos, Desde Ventana Estudiante
*/
package asignacion.vista;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import asignacion.dominio.AsignacionCursos;
import asignacion.datos.AsignacionCursosDAO;

public class AsignacionDeCursos extends javax.swing.JPanel {

    String cod, bpago, semtrim, yearas;
    String c1,c2,c3,c4,c5,ce1,ce2,ce3;
    String name,apellido;
    
    public AsignacionDeCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCarne = new javax.swing.JTextField();
        lblBPago = new javax.swing.JTextField();
        lblYear = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCurso1 = new javax.swing.JLabel();
        txtCurso2 = new javax.swing.JLabel();
        txtCurso3 = new javax.swing.JLabel();
        txtCurso4 = new javax.swing.JLabel();
        txtCurso5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        btnAsignar = new javax.swing.JButton();
        txtCursoE1 = new javax.swing.JLabel();
        txtCursoE2 = new javax.swing.JLabel();
        txtCursoE3 = new javax.swing.JLabel();
        CboxC1 = new javax.swing.JComboBox<>();
        CboxC2 = new javax.swing.JComboBox<>();
        CboxC3 = new javax.swing.JComboBox<>();
        CboxC4 = new javax.swing.JComboBox<>();
        CboxC5 = new javax.swing.JComboBox<>();
        CboxCE1 = new javax.swing.JComboBox<>();
        CboxCE2 = new javax.swing.JComboBox<>();
        CboxCE3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        CboxST = new javax.swing.JComboBox<>();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jTextField1.setText("jTextField1");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Curso 1 :");

        jList8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jList8.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Selecciona", "A (Horarios)", "B (Horarios)" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList8);

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Boleta De Pago :");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Carnet :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Semestre / Trimestre  :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Año  :");

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Cursos Ordinarios");

        txtCurso1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCurso1.setText("Curso 1 :");

        txtCurso2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCurso2.setText("Curso 2 :");

        txtCurso3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCurso3.setText("Curso 3 :");

        txtCurso4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCurso4.setText("Curso 4 :");

        txtCurso5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCurso5.setText("Curso 5 :");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Cursos Extraordinarios");

        btnAsignar.setText("Asignar");
        btnAsignar.setPreferredSize(new java.awt.Dimension(85, 38));
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        txtCursoE1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCursoE1.setText("Curso 1 :");

        txtCursoE2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCursoE2.setText("Curso 2 :");

        txtCursoE3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCursoE3.setText("Curso 3 :");

        CboxC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxC2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxC3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxC4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxC5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxCE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxCE2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        CboxCE3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seccion", "A (Horarios)", "B (Horarios)" }));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Nombre :");

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCurso5)
                        .addGap(18, 18, 18)
                        .addComponent(CboxC5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCurso2)
                        .addGap(18, 18, 18)
                        .addComponent(CboxC2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCurso3)
                        .addGap(18, 18, 18)
                        .addComponent(CboxC3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCurso4)
                        .addGap(18, 18, 18)
                        .addComponent(CboxC4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCurso1)
                        .addGap(18, 18, 18)
                        .addComponent(CboxC1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCursoE1)
                                .addGap(18, 18, 18)
                                .addComponent(CboxCE1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCursoE2)
                                .addGap(18, 18, 18)
                                .addComponent(CboxCE2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCursoE3)
                                .addGap(18, 18, 18)
                                .addComponent(CboxCE3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCurso1)
                                    .addComponent(CboxC1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCurso2)
                                    .addComponent(CboxC2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCurso3)
                                    .addComponent(CboxC3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCurso4)
                                    .addComponent(CboxC4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCurso5)
                                    .addComponent(CboxC5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(134, 134, 134))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCursoE1)
                                    .addComponent(CboxCE1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCursoE2)
                                    .addComponent(CboxCE2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCursoE3)
                                    .addComponent(CboxCE3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnIngresar.setText("Ingresar");
        btnIngresar.setMaximumSize(new java.awt.Dimension(85, 38));
        btnIngresar.setMinimumSize(new java.awt.Dimension(85, 38));
        btnIngresar.setPreferredSize(new java.awt.Dimension(85, 38));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        CboxST.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "1", "2", "3", "4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCarne)
                            .addComponent(lblBPago, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CboxST, 0, 115, Short.MAX_VALUE)
                            .addComponent(lblYear))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(637, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBPago, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CboxST, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblYear)
                                .addGap(55, 55, 55)))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        cod = lblCarne.getText();
        bpago = lblBPago.getText();
        semtrim = CboxST.getSelectedItem().toString();
        yearas = lblYear.getText();
        
        AsignacionCursos cursobusqueda = new AsignacionCursos();
        AsignacionCursosDAO cursobusquedaDAO = new AsignacionCursosDAO();
        
        cursobusqueda = cursobusquedaDAO.query(cursobusqueda);
        
        String IdAlumno = (cursobusqueda.getIdAlumnoCD());
        
        if (IdAlumno.equals(cod)){
            txtName.setText(cursobusqueda.getNombres() +" "+ cursobusqueda.getApellidos());
            txtCurso1.setText(cursobusqueda.getCurso1());
            if (cursobusqueda.getIdc1().equals(cursobusqueda.getIdsecyhor())) {CboxC1.addItem(cursobusqueda.getSecA());CboxC1.addItem(cursobusqueda.getSecB()); CboxC1.addItem(cursobusqueda.getSecC()); CboxC1.addItem(cursobusqueda.getSecD());}
            txtCurso2.setText(cursobusqueda.getCurso2());
            if (cursobusqueda.getIdc2().equals(cursobusqueda.getIdsecyhor())) { CboxC2.addItem(cursobusqueda.getSecA()); CboxC2.addItem(cursobusqueda.getSecB()); CboxC2.addItem(cursobusqueda.getSecC()); CboxC2.addItem(cursobusqueda.getSecD());}
            txtCurso3.setText(cursobusqueda.getCurso3());
            if (cursobusqueda.getIdc3().equals(cursobusqueda.getIdsecyhor())) { CboxC3.addItem(cursobusqueda.getSecA()); CboxC3.addItem(cursobusqueda.getSecB()); CboxC3.addItem(cursobusqueda.getSecC()); CboxC3.addItem(cursobusqueda.getSecD());}
            txtCurso4.setText(cursobusqueda.getCurso4());
            if (cursobusqueda.getIdc4().equals(cursobusqueda.getIdsecyhor())) { CboxC4.addItem(cursobusqueda.getSecA()); CboxC4.addItem(cursobusqueda.getSecB()); CboxC4.addItem(cursobusqueda.getSecC()); CboxC4.addItem(cursobusqueda.getSecD());}
            txtCurso5.setText(cursobusqueda.getCurso5());
            if (cursobusqueda.getIdc5().equals(cursobusqueda.getIdsecyhor())) { CboxC5.addItem(cursobusqueda.getSecA()); CboxC5.addItem(cursobusqueda.getSecB()); CboxC5.addItem(cursobusqueda.getSecC()); CboxC5.addItem(cursobusqueda.getSecD());}
            txtCursoE1.setText(cursobusqueda.getCursoe1());
            if (cursobusqueda.getIdce1().equals(cursobusqueda.getIdsecyhor())) { CboxCE1.addItem(cursobusqueda.getSecA()); CboxCE1.addItem(cursobusqueda.getSecB()); CboxCE1.addItem(cursobusqueda.getSecC()); CboxCE1.addItem(cursobusqueda.getSecD());}
            txtCursoE2.setText(cursobusqueda.getCursoe2());
            if (cursobusqueda.getIdce2().equals(cursobusqueda.getIdsecyhor())) { CboxCE2.addItem(cursobusqueda.getSecA()); CboxCE2.addItem(cursobusqueda.getSecB()); CboxCE2.addItem(cursobusqueda.getSecC()); CboxCE2.addItem(cursobusqueda.getSecD());}
            txtCursoE3.setText(cursobusqueda.getCursoe3());
            if (cursobusqueda.getIdce3().equals(cursobusqueda.getIdsecyhor())) { CboxCE3.addItem(cursobusqueda.getSecA()); CboxCE3.addItem(cursobusqueda.getSecB()); CboxCE3.addItem(cursobusqueda.getSecC()); CboxCE3.addItem(cursobusqueda.getSecD());}
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        
        c1 = CboxC1.getSelectedItem().toString();
        c2 = CboxC2.getSelectedItem().toString();
        c3 = CboxC3.getSelectedItem().toString();
        c4 = CboxC4.getSelectedItem().toString();
        c5 = CboxC5.getSelectedItem().toString();
        ce1 = CboxCE1.getSelectedItem().toString();
        ce2 = CboxCE2.getSelectedItem().toString();
        ce3 = CboxCE3.getSelectedItem().toString();
        
        
    }//GEN-LAST:event_btnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxC1;
    private javax.swing.JComboBox<String> CboxC2;
    private javax.swing.JComboBox<String> CboxC3;
    private javax.swing.JComboBox<String> CboxC4;
    private javax.swing.JComboBox<String> CboxC5;
    private javax.swing.JComboBox<String> CboxCE1;
    private javax.swing.JComboBox<String> CboxCE2;
    private javax.swing.JComboBox<String> CboxCE3;
    private javax.swing.JComboBox<String> CboxST;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lblBPago;
    private javax.swing.JTextField lblCarne;
    private javax.swing.JTextField lblYear;
    private javax.swing.JLabel txtCurso1;
    private javax.swing.JLabel txtCurso2;
    private javax.swing.JLabel txtCurso3;
    private javax.swing.JLabel txtCurso4;
    private javax.swing.JLabel txtCurso5;
    private javax.swing.JLabel txtCursoE1;
    private javax.swing.JLabel txtCursoE2;
    private javax.swing.JLabel txtCursoE3;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables

}
